[package]
name = "forgetyping"
version = "0.1.16"
edition = "2021"
authors = ["Saboor Hamedi <saboorhamedi49@gmail.com>"]
description = "A kinetic, ultra-juicy desktop typing game with spring caret physics and real-time velocity graph"
license = "MIT"
repository = "https://github.com/Saboor-Hamedi/typingforge"
homepage = "https://github.com/Saboor-Hamedi/typingforge"
default-run = "forgetyping"

[lib]
name = "forgetyping"
path = "lib.rs"

[[bin]]
name = "forgetyping"
path = "main.rs"

[[bin]]
name = "publish"
path = "bin/publish.rs"

[[bin]]
name = "generate_text"
path = "bin/generate_text.rs"

[dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
egui = "0.29"
rodio = { version = "0.19", default-features = false, features = ["wav"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
chrono = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
argon2 = "0.5"
rfd = "0.15"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
